### ISSUE TITLE
Suboptimal usage of setting memory limit

### ISSUE THREAD

**Issue by mudrd8mz** [ctchanandy/moodle-report_forumkeywords#1]
Places where the code calls
```
ini_set('memory_limit', '1024M');
```
should be replaced with Moodle's core function `raise_memory_limit()`. Among other benefits, some servers may have already higher limit set and your code would actually decrease it.

**Comment by ctchanandy** [comment]
raise_memory_limit(MEMORY_HUGE) is used now instead.
