### ISSUE TITLE
Plugin setting storage

### ISSUE THREAD

**Issue by mudrd8mz** [ctchanandy/moodle-report_forumkeywords#3]
The plugin puts its settings into the global config ($CFG) table. The plugins' settings should go to the config_plugin space.

See https://docs.moodle.org/dev/Plugin_contribution_checklist#Settings_storage

**Comment by ctchanandy** [comment]
Followed this instruction (and also specified the size of the text box).
> In the file settings.php, the setting names are supposed to be plugintype_pluginname/settingname (note the slash) and not plugintype_pluginname_settingname or even just settingname.
