### ISSUE TITLE
It should format text and convert it to plain text prior analysing

### ISSUE THREAD

**Issue by mudrd8mz** [ctchanandy/moodle-report_forumkeywords#9]
It seems the plugin simply calls `strip_tags($m->message)` to extract the forum post. As such, I can then see various keywords that come from HTML tags (such as "href") as frequent keywords.

I think it would produce more reliable results if it
1. Applied `format_text()` first to get the post processed by filters etc.
2. Applied `html_to_text()` then

similarly to how `question_utils::to_plain_text()` does it, for example.

**Comment by ctchanandy** [comment]
Applied the suggested way of cleaning the forum posts:
```
$message_plain = html_to_text(format_text($m->message, $m->messageformat), 0, false);
```
